apiVersion: v1
kind: Service
metadata:
  name: ctf-d1-hidden-app-service
  labels:
    app: ctf-d1-hidden-app
spec:
  selector:
    app: ctf-d1-hidden-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
