apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"trainee-chowdri-debugging-d2-02"},"name":"d2-02-web-service","namespace":"trainee-chowdri"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"web"},"type":"ClusterIP"}}
  creationTimestamp: "2025-11-11T06:30:26Z"
  labels:
    argocd.argoproj.io/instance: trainee-chowdri-debugging-d2-02
  name: d2-02-web-service
  namespace: trainee-chowdri
  resourceVersion: "5050878"
  uid: 77f673f2-6e2c-4c28-9d0b-6a9fc2576072
spec:
  clusterIP: 172.20.32.3
  clusterIPs:
  - 172.20.32.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
