apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"ctf-d1-hidden-app"},"name":"ctf-d1-hidden-app-service","namespace":"trainee-chowdri"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"ctf-d1-hidden-app"},"type":"ClusterIP"}}
  creationTimestamp: "2025-11-12T13:03:20Z"
  labels:
    app: ctf-d1-hidden-app
  name: ctf-d1-hidden-app-service
  namespace: trainee-chowdri
  resourceVersion: "5843217"
  uid: e51660c3-3d4e-4b2f-9536-5055ab90b771
spec:
  clusterIP: 172.20.131.80
  clusterIPs:
  - 172.20.131.80
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ctf-d1-hidden-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
