apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-ctf-d1-01-lost-in-pods:/Service:trainee-chowdri/ctf-d1-lost-pods-svc
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"trainee-chowdri-ctf-d1-01-lost-in-pods:/Service:trainee-chowdri/ctf-d1-lost-pods-svc"},"labels":{"app":"ctf-d1-lost-pods","challenge":"lost-in-pods"},"name":"ctf-d1-lost-pods-svc","namespace":"trainee-chowdri"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"ctf-d1-lost-pods"},"type":"ClusterIP"}}
  creationTimestamp: "2025-11-12T05:11:19Z"
  labels:
    app: ctf-d1-lost-pods
    challenge: lost-in-pods
  name: ctf-d1-lost-pods-svc
  namespace: trainee-chowdri
  resourceVersion: "7058474"
  uid: a075da2a-e9ec-4a8e-9aa9-180866ccdc77
spec:
  clusterIP: 172.20.57.193
  clusterIPs:
  - 172.20.57.193
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ctf-d1-lost-pods
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
