apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-debugging-d4-05:/Service:trainee-chowdri/d4-05-ready-service
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"trainee-chowdri-debugging-d4-05:/Service:trainee-chowdri/d4-05-ready-service"},"labels":{"task":"debugging-d4-05"},"name":"d4-05-ready-service","namespace":"trainee-chowdri"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"ready-app"},"type":"ClusterIP"}}
  creationTimestamp: "2025-11-13T08:13:16Z"
  labels:
    task: debugging-d4-05
  name: d4-05-ready-service
  namespace: trainee-chowdri
  resourceVersion: "6363126"
  uid: 46de9f1a-366d-499d-b47c-d3de88db408b
spec:
  clusterIP: 172.20.11.236
  clusterIPs:
  - 172.20.11.236
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ready-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
