apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-debugging-d4-06:/Service:trainee-chowdri/d4-06-label-service
    description: Service for label-app application
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"trainee-chowdri-debugging-d4-06:/Service:trainee-chowdri/d4-06-label-service","description":"Service for label-app application"},"labels":{"task":"debugging-d4-06"},"name":"d4-06-label-service","namespace":"trainee-chowdri"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"label-app","version":"v1"},"type":"ClusterIP"}}
  creationTimestamp: "2025-11-13T08:13:16Z"
  labels:
    task: debugging-d4-06
  name: d4-06-label-service
  namespace: trainee-chowdri
  resourceVersion: "6363152"
  uid: eab2dc96-cba0-43fe-90c0-ac8ef8ea76fb
spec:
  clusterIP: 172.20.38.104
  clusterIPs:
  - 172.20.38.104
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: label-app
    version: v1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
