apiVersion: v1
kind: Pod
metadata:
  name: huge-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo 'Running huge pod';"]
    resources:
      requests:
        cpu: "12"
        memory: "4Gi"
      limits:
        cpu: "12"
        memory: "4Gi"
  restartPolicy: Never
