FROM python:3.9.25-slim-trixie

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 80

ENV NAME=World

CMD ["python", "main.py"]
