apiVersion: v1
kind: ServiceAccount
metadata:
 name: s3-reader-sa
 annotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::590852515231:role/MinikubeS3Role022
  eks.amazonaws.com/audience: sts.amazonaws.com
