apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-11-12T14:47:14Z"
  generateName: ctf-d1-broken-manifest-deploy-6cc7f6b448-
  labels:
    app: ctf-d1-broken-manifest
    challenge: broken-manifest
    pod-template-hash: 6cc7f6b448
  name: ctf-d1-broken-manifest-deploy-6cc7f6b448-pqtbm
  namespace: trainee-chowdri
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: ctf-d1-broken-manifest-deploy-6cc7f6b448
    uid: 8bcd07da-3fc2-493f-b8a8-b1b2042848d7
  resourceVersion: "5895728"
  uid: 410900cb-401a-40e0-8bbf-cf2f59b0a5c5
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: IfNotPresent
    name: web-app
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 10m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/flag
      name: flag-volume
      subPath: flag
    - mountPath: /etc/nginx/conf.d
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hq5z9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - |
      kubectl get configmap ctf-flag-b3n8q1r -n ctf-admin -o jsonpath='{.data.flag}' > /flag-data/flag
    command:
    - sh
    - -c
    image: bitnami/kubectl:latest
    imagePullPolicy: Always
    name: fetch-flag
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /flag-data
      name: flag-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hq5z9
      readOnly: true
  nodeName: ip-10-0-35-123.ec2.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: ctf-flag-reader
  serviceAccountName: ctf-flag-reader
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: flag-volume
  - configMap:
      defaultMode: 420
      name: ctf-d1-broken-manifest-nginx-config
    name: config-volume
  - name: kube-api-access-hq5z9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-11-12T14:47:16Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-11-12T14:47:17Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-11-12T14:47:18Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-11-12T14:47:18Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-11-12T14:47:14Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://c2392ac0132267625df55cbcfeebbf2c2da4e3c3e65f8d4351f258a1f2d3bf35
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:1beed3ca46acebe9d3fb62e9067f03d05d5bfa97a00f30938a0a3580563272ad
    lastState: {}
    name: web-app
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-11-12T14:47:17Z"
  hostIP: 10.0.35.123
  hostIPs:
  - ip: 10.0.35.123
  initContainerStatuses:
  - containerID: containerd://4d8451ef0d75871df80c7a7b13adaed11afb838013734cc3df9cc9754f7982ce
    image: docker.io/bitnami/kubectl:latest
    imageID: docker.io/bitnami/kubectl@sha256:5df7de31ece99cc40aa34d627a61b1bb4d17d1a3341e2f63a63b46b1136080cd
    lastState: {}
    name: fetch-flag
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://4d8451ef0d75871df80c7a7b13adaed11afb838013734cc3df9cc9754f7982ce
        exitCode: 0
        finishedAt: "2025-11-12T14:47:16Z"
        reason: Completed
        startedAt: "2025-11-12T14:47:16Z"
  phase: Running
  podIP: 10.0.39.26
  podIPs:
  - ip: 10.0.39.26
  qosClass: Burstable
  startTime: "2025-11-12T14:47:14Z"
