apiVersion: v1
kind: Pod
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-debugging-d3-03:/Pod:trainee-chowdri/d3-03-secure-app
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"trainee-chowdri-debugging-d3-03:/Pod:trainee-chowdri/d3-03-secure-app"},"labels":{"app":"secure-app","task":"debugging-d3-03"},"name":"d3-03-secure-app","namespace":"trainee-chowdri"},"spec":{"containers":[{"image":"nginx:latest","name":"app","resources":{"limits":{"cpu":"200m","memory":"128Mi"},"requests":{"cpu":"100m","memory":"64Mi"}},"volumeMounts":[{"mountPath":"/etc/secrets","name":"secret-volume","readOnly":true},{"mountPath":"/etc/db/password","name":"db-creds","readOnly":true,"subPath":"database-password"}]}],"volumes":[{"name":"secret-volume","secret":{"secretName":"d3-03-app-secret"}},{"name":"db-creds","secret":{"secretName":"d3-03-app-secret"}}]}}
  creationTimestamp: "2025-11-14T07:02:36Z"
  labels:
    app: secure-app
    task: debugging-d3-03
  name: d3-03-secure-app
  namespace: trainee-chowdri
  resourceVersion: "7129362"
  uid: 4befc328-a87a-45a0-abdc-a0bf48404755
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: app
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/secrets
      name: secret-volume
      readOnly: true
    - mountPath: /etc/db/password
      name: db-creds
      readOnly: true
      subPath: database-password
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mb2mv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-0-47-199.ec2.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: secret-volume
    secret:
      defaultMode: 420
      secretName: d3-03-app-secret
  - name: db-creds
    secret:
      defaultMode: 420
      secretName: d3-03-app-secret
  - name: kube-api-access-mb2mv
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-11-14T07:02:37Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-11-14T07:02:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-11-14T07:02:37Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-11-14T07:02:37Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-11-14T07:02:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://3758a136ff287258ab8bd9780e17e587146a1c38753ac89a54da65d0cd7ff826
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:1beed3ca46acebe9d3fb62e9067f03d05d5bfa97a00f30938a0a3580563272ad
    lastState: {}
    name: app
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-11-14T07:02:37Z"
  hostIP: 10.0.47.199
  hostIPs:
  - ip: 10.0.47.199
  phase: Running
  podIP: 10.0.32.17
  podIPs:
  - ip: 10.0.32.17
  qosClass: Burstable
  startTime: "2025-11-14T07:02:36Z"
