apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"global-efs","namespace":"trainee-chowdri"},"spec":{"containers":[{"command":["sh","-c","while true; do echo 'Hello from EFS' \u003e\u003e /data/out.txt; sleep 5; done"],"image":"busybox","name":"app","volumeMounts":[{"mountPath":"/data","name":"efs-storage"}]}],"volumes":[{"name":"efs-storage","persistentVolumeClaim":{"claimName":"global-efs-pvc"}}]}}
  creationTimestamp: "2025-11-14T06:45:52Z"
  name: global-efs
  namespace: trainee-chowdri
  resourceVersion: "7116473"
  uid: 255206e7-1eef-4628-ae97-6cd1d6972c18
spec:
  containers:
  - command:
    - sh
    - -c
    - while true; do echo 'Hello from EFS' >> /data/out.txt; sleep 5; done
    image: busybox
    imagePullPolicy: Always
    name: app
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: efs-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-p4dv6
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-0-19-16.ec2.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: efs-storage
    persistentVolumeClaim:
      claimName: global-efs-pvc
  - name: kube-api-access-p4dv6
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-11-14T06:45:54Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-11-14T06:45:52Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-11-14T06:45:54Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-11-14T06:45:54Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-11-14T06:45:52Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://d1beca12c4b06a9fedafde7d04c46b5867c95c159467cf30e042611776b90c05
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:e3652a00a2fabd16ce889f0aa32c38eec347b997e73bd09e69c962ec7f8732ee
    lastState: {}
    name: app
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-11-14T06:45:54Z"
  hostIP: 10.0.19.16
  hostIPs:
  - ip: 10.0.19.16
  phase: Running
  podIP: 10.0.16.52
  podIPs:
  - ip: 10.0.16.52
  qosClass: BestEffort
  startTime: "2025-11-14T06:45:52Z"
