apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-ctf-d2-03-quota-madness:apps/Deployment:trainee-chowdri/ctf-d2-quota-madness
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"trainee-chowdri-ctf-d2-03-quota-madness:apps/Deployment:trainee-chowdri/ctf-d2-quota-madness"},"labels":{"app":"ctf-d2-quota-madness","challenge":"d2-quota-madness"},"name":"ctf-d2-quota-madness","namespace":"trainee-chowdri"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ctf-d2-quota-madness"}},"template":{"metadata":{"labels":{"app":"ctf-d2-quota-madness","challenge":"d2-quota-madness"}},"spec":{"containers":[{"image":"nginx:alpine","name":"app","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"2","memory":"256Mi"},"requests":{"cpu":"2","memory":"128Mi"}},"volumeMounts":[{"mountPath":"/etc/flag","name":"flag-volume","subPath":"flag"},{"mountPath":"/etc/nginx/conf.d","name":"config-volume"}]}],"initContainers":[{"args":["kubectl get configmap ctf-flag-i5w1x2y -n ctf-admin -o jsonpath='{.data.flag}' \u003e /flag-data/flag\n"],"command":["sh","-c"],"image":"bitnami/kubectl:latest","name":"fetch-flag","resources":{"limits":{"cpu":"50m","memory":"64Mi"},"requests":{"cpu":"25m","memory":"32Mi"}},"volumeMounts":[{"mountPath":"/flag-data","name":"flag-volume"}]}],"serviceAccountName":"ctf-flag-reader","volumes":[{"emptyDir":{},"name":"flag-volume"},{"configMap":{"name":"ctf-d2-quota-nginx-config"},"name":"config-volume"}]}}}}
  creationTimestamp: "2025-11-14T07:36:11Z"
  generation: 1
  labels:
    app: ctf-d2-quota-madness
    challenge: d2-quota-madness
  name: ctf-d2-quota-madness
  namespace: trainee-chowdri
  resourceVersion: "7158750"
  uid: 342dc554-5618-44fb-92f8-bfaa73714d15
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ctf-d2-quota-madness
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctf-d2-quota-madness
        challenge: d2-quota-madness
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 256Mi
          requests:
            cpu: "2"
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/flag
          name: flag-volume
          subPath: flag
        - mountPath: /etc/nginx/conf.d
          name: config-volume
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - |
          kubectl get configmap ctf-flag-i5w1x2y -n ctf-admin -o jsonpath='{.data.flag}' > /flag-data/flag
        command:
        - sh
        - -c
        image: bitnami/kubectl:latest
        imagePullPolicy: Always
        name: fetch-flag
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 25m
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /flag-data
          name: flag-volume
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ctf-flag-reader
      serviceAccountName: ctf-flag-reader
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: flag-volume
      - configMap:
          defaultMode: 420
          name: ctf-d2-quota-nginx-config
        name: config-volume
status:
  conditions:
  - lastTransitionTime: "2025-11-14T07:36:11Z"
    lastUpdateTime: "2025-11-14T07:36:11Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-11-14T07:36:11Z"
    lastUpdateTime: "2025-11-14T07:36:11Z"
    message: 'pods "ctf-d2-quota-madness-7847b76775-2lthd" is forbidden: exceeded
      quota: d3-05-namespace-quota, requested: limits.cpu=2,limits.memory=256Mi,pods=1,requests.cpu=2,requests.memory=128Mi,
      used: limits.cpu=3030m,limits.memory=2880Mi,pods=22,requests.cpu=1520m,requests.memory=1440Mi,
      limited: limits.cpu=1,limits.memory=1Gi,pods=5,requests.cpu=500m,requests.memory=512Mi'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  - lastTransitionTime: "2025-11-14T07:46:12Z"
    lastUpdateTime: "2025-11-14T07:46:12Z"
    message: ReplicaSet "ctf-d2-quota-madness-7847b76775" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  unavailableReplicas: 1
