apiVersion: v1
kind: Pod
metadata:
  name: s3-reader
  namespace: default
spec:
  serviceAccountName: s3-reader-sa
  containers:
  - name: read-s3
    image: amazon/aws-cli
    command: ["sh", "-c"]
    args:
    - |
      aws s3 ls s3://chow3-bucket-022
      sleep 7000
    env:
    - name: AWS_REGION
      value: us-east-1