#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/package
- name: Install Apache
  apt:
    name:
      - apache2
    state: present

- name: Install mysql-server
  apt:
    name:
      - mysql-server
    state: present

- name: Install PHP
  apt:
    name:
      - php
    state: present