events {}

http {
    upstream flask1 {
        server flask1:80;
    }

    upstream flask2 {
        server flask2:80;
    }

    upstream flask3 {
        server flask3:80;
    }

    server {
        listen 80;

        location /app1/ {
            rewrite ^/app1/(.*)$ /$1 break;
            proxy_pass http://flask1/;
        }

        location /app2/ {
            rewrite ^/app2/(.*)$ /$1 break;
            proxy_pass http://flask2/;
        }

        location /app3/ {
            rewrite ^/app3/(.*)$ /$1 break;
            proxy_pass http://flask3/;
        }
    }
}
