apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-ctf-d2-02-secret-leak:apps/Deployment:trainee-chowdri/ctf-d2-secret-leak
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-11-14T07:36:08Z"
  generation: 1
  labels:
    app: ctf-d2-secret-leak
    challenge: d2-secret-leak
    pod-template-hash: 74f845b9fd
  name: ctf-d2-secret-leak-74f845b9fd
  namespace: trainee-chowdri
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: ctf-d2-secret-leak
    uid: ec2e9fa2-e2db-4f2f-aba2-ae7a8b1627aa
  resourceVersion: "7150060"
  uid: 0a743097-d1ca-4974-b589-1134bf15ef2d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-d2-secret-leak
      pod-template-hash: 74f845b9fd
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctf-d2-secret-leak
        challenge: d2-secret-leak
        pod-template-hash: 74f845b9fd
    spec:
      containers:
      - args:
        - echo starting; echo DB_PASSWORD=$DB_PASSWORD; FLAG=$(cat /etc/flag/flag
          2>/dev/null || echo 'FLAG_NOT_FOUND'); while true; do echo $FLAG >> /proc/1/fd/1;
          sleep 60; done
        command:
        - /bin/sh
        - -c
        env:
        - name: DB_PASSWORD
          value: admin123
        image: busybox:1.36
        imagePullPolicy: IfNotPresent
        name: web-app
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 25m
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/flag
          name: flag-volume
          subPath: flag
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - |
          kubectl get configmap ctf-flag-g3q6r8s -n ctf-admin -o jsonpath='{.data.flag}' > /flag-data/flag
        command:
        - sh
        - -c
        image: bitnami/kubectl:latest
        imagePullPolicy: Always
        name: fetch-flag
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /flag-data
          name: flag-volume
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ctf-flag-reader
      serviceAccountName: ctf-flag-reader
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: flag-volume
status:
  conditions:
  - lastTransitionTime: "2025-11-14T07:36:08Z"
    message: 'pods "ctf-d2-secret-leak-74f845b9fd-58xbl" is forbidden: failed quota:
      d3-05-namespace-quota: must specify limits.cpu for: fetch-flag; limits.memory
      for: fetch-flag; requests.cpu for: fetch-flag; requests.memory for: fetch-flag'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 1
  replicas: 0
