apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-debugging-d4-05:apps/Deployment:trainee-chowdri/d4-05-ready-app
    deployment.kubernetes.io/desired-replicas: "2"
    deployment.kubernetes.io/max-replicas: "3"
    deployment.kubernetes.io/revision: "7"
  creationTimestamp: "2025-11-14T09:15:32Z"
  generation: 2
  labels:
    app: ready-app
    pod-template-hash: 5cb94c6c
    task: debugging-d4-05
  name: d4-05-ready-app-5cb94c6c
  namespace: trainee-chowdri
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: d4-05-ready-app
    uid: 8bb7c4ba-8aae-468a-9595-607947bc3317
  resourceVersion: "7209623"
  uid: 4ab522fd-528b-4a81-a471-2420a56ef08c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ready-app
      pod-template-hash: 5cb94c6c
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-11-14T14:45:32+05:30"
      creationTimestamp: null
      labels:
        app: ready-app
        pod-template-hash: 5cb94c6c
        task: debugging-d4-05
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: web-server
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-11-14T09:15:32Z"
    message: 'pods "d4-05-ready-app-5cb94c6c-hz65w" is forbidden: exceeded quota:
      ctf-d2-quota, requested: limits.cpu=50m,limits.memory=128Mi,requests.cpu=50m,requests.memory=64Mi,
      used: limits.cpu=2630m,limits.memory=2624Mi,requests.cpu=1320m,requests.memory=1312Mi,
      limited: limits.cpu=1,limits.memory=512Mi,requests.cpu=500m,requests.memory=256Mi'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 2
  replicas: 0
