apiVersion: v1
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        location / {
            return 200 "Welcome to CloudCorp - Challenge 2 Complete!\n";
            add_header Content-Type text/plain;
        }
        location /flag {
            alias /etc/flag;
            default_type text/plain;
            add_header Content-Type text/plain;
        }
    }
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-ctf-d1-01-lost-in-pods:/ConfigMap:trainee-chowdri/ctf-d1-lost-pods-nginx-config
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"default.conf":"server {\n    listen 80;\n    server_name _;\n    location / {\n        return 200 \"Welcome to CloudCorp - Challenge 2 Complete!\\n\";\n        add_header Content-Type text/plain;\n    }\n    location /flag {\n        alias /etc/flag;\n        default_type text/plain;\n        add_header Content-Type text/plain;\n    }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"trainee-chowdri-ctf-d1-01-lost-in-pods:/ConfigMap:trainee-chowdri/ctf-d1-lost-pods-nginx-config"},"labels":{"challenge":"lost-in-pods"},"name":"ctf-d1-lost-pods-nginx-config","namespace":"trainee-chowdri"}}
  creationTimestamp: "2025-11-12T05:11:19Z"
  labels:
    challenge: lost-in-pods
  name: ctf-d1-lost-pods-nginx-config
  namespace: trainee-chowdri
  resourceVersion: "7058433"
  uid: a5120391-7da6-4612-82c1-066df4b14e3c
