apiVersion: v1
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        location / {
            return 200 "LimitRange Trap Challenge Complete!\n\nYou successfully added resource requests/limits to meet LimitRange requirements.\n\nAccess the flag at /flag\n";
            add_header Content-Type text/plain;
        }
        location /flag {
            alias /etc/flag;
            default_type text/plain;
            add_header Content-Type text/plain;
        }
    }
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-ctf-d2-04-limitrange-trap:/ConfigMap:trainee-chowdri/ctf-d2-limitrange-nginx-config
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"default.conf":"server {\n    listen 80;\n    server_name _;\n    location / {\n        return 200 \"LimitRange Trap Challenge Complete!\\n\\nYou successfully added resource requests/limits to meet LimitRange requirements.\\n\\nAccess the flag at /flag\\n\";\n        add_header Content-Type text/plain;\n    }\n    location /flag {\n        alias /etc/flag;\n        default_type text/plain;\n        add_header Content-Type text/plain;\n    }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"trainee-chowdri-ctf-d2-04-limitrange-trap:/ConfigMap:trainee-chowdri/ctf-d2-limitrange-nginx-config"},"labels":{"challenge":"d2-limitrange-trap"},"name":"ctf-d2-limitrange-nginx-config","namespace":"trainee-chowdri"}}
  creationTimestamp: "2025-11-14T07:36:13Z"
  labels:
    challenge: d2-limitrange-trap
  name: ctf-d2-limitrange-nginx-config
  namespace: trainee-chowdri
  resourceVersion: "7150892"
  uid: e2fa43df-60aa-4196-a29f-944b480b54fe
