apiVersion: v1
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        location / {
            return 200 "Welcome to CloudCorp - Challenge 3 Complete!\n";
            add_header Content-Type text/plain;
        }
    }
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-ctf-d1-02-broken-manifest:/ConfigMap:trainee-chowdri/ctf-d1-broken-manifest-nginx-config
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"default.conf":"server {\n    listen 80;\n    server_name _;\n    location / {\n        return 200 \"Welcome to CloudCorp - Challenge 3 Complete!\\n\";\n        add_header Content-Type text/plain;\n    }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"trainee-chowdri-ctf-d1-02-broken-manifest:/ConfigMap:trainee-chowdri/ctf-d1-broken-manifest-nginx-config"},"labels":{"challenge":"broken-manifest"},"name":"ctf-d1-broken-manifest-nginx-config","namespace":"trainee-chowdri"}}
  creationTimestamp: "2025-11-12T05:11:17Z"
  labels:
    challenge: broken-manifest
  name: ctf-d1-broken-manifest-nginx-config
  namespace: trainee-chowdri
  resourceVersion: "7058484"
  uid: 72e90245-1a46-4c2e-a8e8-c8015288043b
