apiVersion: v1
data:
  app.conf: |
    FEATURE_X=true
    MODE=production
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-ctf-d2-01-misconfigured-configmap:/ConfigMap:trainee-chowdri/ctf-d2-app-config
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"app.conf":"FEATURE_X=true\nMODE=production\n"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"trainee-chowdri-ctf-d2-01-misconfigured-configmap:/ConfigMap:trainee-chowdri/ctf-d2-app-config"},"labels":{"challenge":"d2-configmap-injection"},"name":"ctf-d2-app-config","namespace":"trainee-chowdri"}}
  creationTimestamp: "2025-11-14T07:36:09Z"
  labels:
    challenge: d2-configmap-injection
  name: ctf-d2-app-config
  namespace: trainee-chowdri
  resourceVersion: "7150135"
  uid: 98e63b89-5cd8-4e83-a35c-0fd99c6f3834
