apiVersion: v1
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        location / {
            return 200 "Quota Madness Challenge Complete!\n\nYou successfully reduced CPU requests to fit within namespace quota.\n\nAccess the flag at /flag\n";
            add_header Content-Type text/plain;
        }
        location /flag {
            alias /etc/flag;
            default_type text/plain;
            add_header Content-Type text/plain;
        }
    }
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-ctf-d2-03-quota-madness:/ConfigMap:trainee-chowdri/ctf-d2-quota-nginx-config
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"default.conf":"server {\n    listen 80;\n    server_name _;\n    location / {\n        return 200 \"Quota Madness Challenge Complete!\\n\\nYou successfully reduced CPU requests to fit within namespace quota.\\n\\nAccess the flag at /flag\\n\";\n        add_header Content-Type text/plain;\n    }\n    location /flag {\n        alias /etc/flag;\n        default_type text/plain;\n        add_header Content-Type text/plain;\n    }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"trainee-chowdri-ctf-d2-03-quota-madness:/ConfigMap:trainee-chowdri/ctf-d2-quota-nginx-config"},"labels":{"challenge":"d2-quota-madness"},"name":"ctf-d2-quota-nginx-config","namespace":"trainee-chowdri"}}
  creationTimestamp: "2025-11-14T07:36:11Z"
  labels:
    challenge: d2-quota-madness
  name: ctf-d2-quota-nginx-config
  namespace: trainee-chowdri
  resourceVersion: "7150573"
  uid: fe01afe7-e099-426b-85cb-3b5c24a9b2b3
