apiVersion: v1
data:
  APP_ENV: production
  APP_NAME: MyWebApp
  CACHE_ENABLED: "true"
  MAX_CONNECTIONS: "100"
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-debugging-d3-04:/ConfigMap:trainee-chowdri/d3-04-app-config
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"APP_ENV":"production","APP_NAME":"MyWebApp","CACHE_ENABLED":"true","MAX_CONNECTIONS":"100"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"trainee-chowdri-debugging-d3-04:/ConfigMap:trainee-chowdri/d3-04-app-config"},"name":"d3-04-app-config","namespace":"trainee-chowdri"}}
  creationTimestamp: "2025-11-14T07:02:36Z"
  name: d3-04-app-config
  namespace: trainee-chowdri
  resourceVersion: "7129289"
  uid: afc48f22-8cac-44d5-b94b-65727671a8f7
