apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0BkYjo1NDMyL215ZGI=
  JWT_SECRET: c3VwZXItc2VjcmV0LWp3dC1rZXktMTIzNDU=
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-debugging-d3-04:/Secret:trainee-chowdri/d3-04-app-credentials
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"trainee-chowdri-debugging-d3-04:/Secret:trainee-chowdri/d3-04-app-credentials"},"name":"d3-04-app-credentials","namespace":"trainee-chowdri"},"stringData":{"DATABASE_URL":"postgresql://user:pass@db:5432/mydb","JWT_SECRET":"super-secret-jwt-key-12345"},"type":"Opaque"}
  creationTimestamp: "2025-11-14T07:02:36Z"
  name: d3-04-app-credentials
  namespace: trainee-chowdri
  resourceVersion: "7129285"
  uid: d508fda3-9700-482b-808e-5996741424bd
type: Opaque
