apiVersion: v1
data:
  api-key: YWJjZGVmMTIzNDU2Nzg5MA==
  db-password: bXlzZWNyZXRwYXNzd29yZDEyMw==
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: trainee-chowdri-debugging-d3-03:/Secret:trainee-chowdri/d3-03-app-secret
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"trainee-chowdri-debugging-d3-03:/Secret:trainee-chowdri/d3-03-app-secret"},"name":"d3-03-app-secret","namespace":"trainee-chowdri"},"stringData":{"api-key":"abcdef1234567890","db-password":"mysecretpassword123"},"type":"Opaque"}
  creationTimestamp: "2025-11-14T07:02:36Z"
  name: d3-03-app-secret
  namespace: trainee-chowdri
  resourceVersion: "7129249"
  uid: fa380fef-0d42-4a0c-906b-ba899b39f994
type: Opaque
