apiVersion: v1
kind: Pod
metadata:
  name: secret-vol-demo
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "ls /etc/secret-vol && cat /etc/secret-vol/user && cat /etc/secret-vol/password"]
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secret-vol"
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: csrt
  restartPolicy: Never
