[web]
nginx ansible_host=13.217.49.156 ansible_user=ubuntu ansible_become=yes ansible_ssh_private_key_file=~/Downloads/bastion.pem
[db]
sql  ansible_host=3.81.216.96 ansible_user=ubuntu ansible_become=yes ansible_ssh_private_key_file=~/Downloads/bastion.pem
